server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 301 $scheme://$http_host/website/;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location ~* \.(css|js)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    location = /config.js {
        proxy_pass         http://leads-api:3100;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
    }

    location /api/ {
        proxy_pass         http://leads-api:3100;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        add_header         Access-Control-Allow-Origin *;
        add_header         Access-Control-Allow-Headers "Content-Type";
        if ($request_method = OPTIONS) { return 204; }
    }

    location /leads-admin {
        proxy_pass         http://leads-api:3100;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /website/404.html;
    location = /website/404.html { internal; }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_min_length 1024;
}
