name: Deploy a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en servidor GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.31.201.58
          username: ederbarrios
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            sudo git -C /home/ederb1_1c/luxuryhorizon pull
            cd /home/ederb1_1c/luxuryhorizon && sudo docker compose up -d --build
